version = 1

[[annotations]]
path = [
  ".gitignore",
  "README.md",
  "sbctl.conf",
]
SPDX-FileCopyrightText = [
    "Timothée Ravier <tim@siosm.fr>",
]
SPDX-License-Identifier = "CC0-1.0"

# Certificate and keys are not copyrightable
[[annotations]]
path = [
  "keys/**",
  "fedora-atomic-desktops-sealed.pub",
]
SPDX-FileCopyrightText = [
    "NONE",
]
SPDX-License-Identifier = "CC0-1.0"
