# SPDX-FileCopyrightText: Timothée Ravier <tim@siosm.fr>
# SPDX-License-Identifier: CC0-1.0

name: "Build Sealed Bootable Container images"

env:
  REGISTRY_GHCR: "ghcr.io/${{ github.repository_owner }}"
  REGISTRY_QUAY: "quay.io"
  REPO_NAME: "${{ github.event.repository.name }}"

on:
  push:
    branches:
      - "main"
    paths:
      - "Containerfile"
      - "scripts/**"
      - ".github/workflows/bootable-containers.yml"
      - ".github/workflows/generate-matrix.yml"
  # We will need a distinct workflow for pull request builds as we will not
  # have access to secrets for signing in those.
  # pull_request:
  #   branches:
  #     - "main"
  schedule:
    - cron: '0 4 * * MON'
  workflow_dispatch:
    inputs:
      version:
        description: "Version (tag) to date the images for. Defaults to today's tag"
        required: false
        default: ''

# Allow:
# - Read access to the repo content
# - Write access to packages to allow access to GitHub container registry
permissions:
  contents: "read"
  packages: "write"

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentialy for the main branch. Also cancel in progress workflow runs for
# pull requests only.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-matrix:
    uses: ./.github/workflows/generate-matrix.yml
    with:
      version: ${{ inputs.version }}

  build-image:
    needs: generate-matrix
    runs-on: "ubuntu-24.04"
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v7

      - name: "Runner setup"
        uses: travier/bootc-dev-actions/bootc-ubuntu-setup@main

      - name: "Login to Container Registry (ghcr.io)"
        uses: redhat-actions/podman-login@v1
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          registry: ${{ env.REGISTRY_GHCR }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Get Secure Boot signing key"
        run: |
          mkdir -p /tmp/keys
          printenv SB_KEY > /tmp/keys/key
          printenv SB_CRT > /tmp/keys/crt
        env:
          SB_KEY: ${{ secrets.SB_KEY }}
          SB_CRT: ${{ secrets.SB_CRT }}

      - name: "Build kernel container image"
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.REPO_NAME }}/${{ matrix.variant }}-kernel
          tags: |
              ${{ matrix.fedora_release }}
              ${{ matrix.fedora_release }}.${{ needs.generate-matrix.outputs.version }}
          containerfiles: Containerfile.kernel
          oci: true
          build-args: |
            BASE=${{ matrix.image_url }}:${{ matrix.tag }}

      - name: "Build base container image"
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.REPO_NAME }}/${{ matrix.variant }}-base
          tags: |
              ${{ matrix.fedora_release }}
              ${{ matrix.fedora_release }}.${{ needs.generate-matrix.outputs.version }}
          containerfiles: Containerfile.base
          oci: true
          build-args: |
            BASE=${{ matrix.image_url }}:${{ matrix.tag }}
          extra-args: |
            --skip-unused-stages=false
            --security-opt=label=disable
            --volume /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}:/run/src

      - name: "Build Generic UKI container image"
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.REPO_NAME }}/${{ matrix.variant }}
          tags: |
              ${{ matrix.fedora_release }}
              ${{ matrix.fedora_release }}.${{ needs.generate-matrix.outputs.version }}
          containerfiles: Containerfile.uki
          oci: true
          build-args: |
            BASE=${{ env.REPO_NAME }}/${{ matrix.variant }}-base:${{ matrix.fedora_release }}.${{ needs.generate-matrix.outputs.version }}
            KERNEL=${{ env.REPO_NAME }}/${{ matrix.variant }}-kernel:${{ matrix.fedora_release }}.${{ needs.generate-matrix.outputs.version }}
            GPU_FAMILY="generic"
            TOOLS=${{ env.REGISTRY_GHCR }}/${{ env.REPO_NAME }}/tools:${{ matrix.fedora_release }}
          extra-args: |
            --security-opt=label=disable
            --volume /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}:/run/src
            --secret=id=secureboot_key,src=/tmp/keys/key
            --secret=id=secureboot_crt,src=/tmp/keys/crt

      - name: "Build Intel UKI container image"
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.REPO_NAME }}/${{ matrix.variant }}-intel
          tags: |
              ${{ matrix.fedora_release }}
              ${{ matrix.fedora_release }}.${{ needs.generate-matrix.outputs.version }}
          containerfiles: Containerfile.uki
          oci: true
          build-args: |
            BASE=${{ env.REPO_NAME }}/${{ matrix.variant }}-base:${{ matrix.fedora_release }}.${{ needs.generate-matrix.outputs.version }}
            KERNEL=${{ env.REPO_NAME }}/${{ matrix.variant }}-kernel:${{ matrix.fedora_release }}.${{ needs.generate-matrix.outputs.version }}
            GPU_FAMILY="intel"
            TOOLS=${{ env.REGISTRY_GHCR }}/${{ env.REPO_NAME }}/tools:${{ matrix.fedora_release }}
          extra-args: |
            --security-opt=label=disable
            --volume /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}:/run/src
            --secret=id=secureboot_key,src=/tmp/keys/key
            --secret=id=secureboot_crt,src=/tmp/keys/crt

      - name: "Build AMD UKI container image"
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.REPO_NAME }}/${{ matrix.variant }}-amd
          tags: |
              ${{ matrix.fedora_release }}
              ${{ matrix.fedora_release }}.${{ needs.generate-matrix.outputs.version }}
          containerfiles: Containerfile.uki
          oci: true
          build-args: |
            BASE=${{ env.REPO_NAME }}/${{ matrix.variant }}-base:${{ matrix.fedora_release }}.${{ needs.generate-matrix.outputs.version }}
            KERNEL=${{ env.REPO_NAME }}/${{ matrix.variant }}-kernel:${{ matrix.fedora_release }}.${{ needs.generate-matrix.outputs.version }}
            GPU_FAMILY="amd"
            TOOLS=${{ env.REGISTRY_GHCR }}/${{ env.REPO_NAME }}/tools:${{ matrix.fedora_release }}
          extra-args: |
            --security-opt=label=disable
            --volume /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}:/run/src
            --secret=id=secureboot_key,src=/tmp/keys/key
            --secret=id=secureboot_crt,src=/tmp/keys/crt

      - name: "Build NVIDIA UKI container image"
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.REPO_NAME }}/${{ matrix.variant }}-nvidia
          tags: |
              ${{ matrix.fedora_release }}
              ${{ matrix.fedora_release }}.${{ needs.generate-matrix.outputs.version }}
          containerfiles: Containerfile.uki
          oci: true
          build-args: |
            BASE=${{ env.REPO_NAME }}/${{ matrix.variant }}-base:${{ matrix.fedora_release }}.${{ needs.generate-matrix.outputs.version }}
            KERNEL=${{ env.REPO_NAME }}/${{ matrix.variant }}-kernel:${{ matrix.fedora_release }}.${{ needs.generate-matrix.outputs.version }}
            GPU_FAMILY="nvidia"
            TOOLS=${{ env.REGISTRY_GHCR }}/${{ env.REPO_NAME }}/tools:${{ matrix.fedora_release }}
          extra-args: |
            --security-opt=label=disable
            --volume /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}:/run/src
            --secret=id=secureboot_key,src=/tmp/keys/key
            --secret=id=secureboot_crt,src=/tmp/keys/crt

      - name: "Cleanup Secure Boot signing key"
        if: always()
        run: rm -vrf /tmp/keys

      - name: "Setup cosign"
        uses: sigstore/cosign-installer@v3.10.0
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'

      - name: "Push generic image to Container Registry (ghcr.io)"
        uses: redhat-actions/push-to-registry@v3
        id: push
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ env.REPO_NAME }}/${{ matrix.variant }}
          registry: ${{ env.REGISTRY_GHCR }}
          tags: |
              ${{ matrix.fedora_release }}
              ${{ matrix.fedora_release }}.${{ needs.generate-matrix.outputs.version }}

      - name: "Push Intel image to Container Registry (ghcr.io)"
        uses: redhat-actions/push-to-registry@v3
        id: push_intel
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ env.REPO_NAME }}/${{ matrix.variant }}-intel
          registry: ${{ env.REGISTRY_GHCR }}
          tags: |
              ${{ matrix.fedora_release }}
              ${{ matrix.fedora_release }}.${{ needs.generate-matrix.outputs.version }}

      - name: "Push AMD image to Container Registry (ghcr.io)"
        uses: redhat-actions/push-to-registry@v3
        id: push_amd
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ env.REPO_NAME }}/${{ matrix.variant }}-amd
          registry: ${{ env.REGISTRY_GHCR }}
          tags: |
              ${{ matrix.fedora_release }}
              ${{ matrix.fedora_release }}.${{ needs.generate-matrix.outputs.version }}

      - name: "Push NVIDIA image to Container Registry (ghcr.io)"
        uses: redhat-actions/push-to-registry@v3
        id: push_nvidia
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ env.REPO_NAME }}/${{ matrix.variant }}-nvidia
          registry: ${{ env.REGISTRY_GHCR }}
          tags: |
              ${{ matrix.fedora_release }}
              ${{ matrix.fedora_release }}.${{ needs.generate-matrix.outputs.version }}

      - name: "Sign generic container image (ghcr.io)"
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ env.REGISTRY_GHCR }}/${{ env.REPO_NAME }}/${{ matrix.variant }}@${{ steps.push.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

      - name: "Sign Intel container image (ghcr.io)"
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ env.REGISTRY_GHCR }}/${{ env.REPO_NAME }}/${{ matrix.variant }}-intel@${{ steps.push_intel.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

      - name: "Sign AMD container image (ghcr.io)"
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ env.REGISTRY_GHCR }}/${{ env.REPO_NAME }}/${{ matrix.variant }}-amd@${{ steps.push_amd.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

      - name: "Sign NVIDIA container image (ghcr.io)"
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ env.REGISTRY_GHCR }}/${{ env.REPO_NAME }}/${{ matrix.variant }}-nvidia@${{ steps.push_nvidia.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

      - name: "Login to Container Registry (quay.io)"
        uses: redhat-actions/podman-login@v1
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          registry: ${{ env.REGISTRY_QUAY }}
          username: ${{ secrets.BOT_USERNAME }}
          password: ${{ secrets.BOT_SECRET }}

      - name: "Push generic image to Container Registry (quay.io)"
        uses: redhat-actions/push-to-registry@v3
        id: push_quay_io
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          username: ${{ secrets.BOT_USERNAME }}
          password: ${{ secrets.BOT_SECRET }}
          image: ${{ env.REPO_NAME }}/${{ matrix.variant }}
          registry: ${{ env.REGISTRY_QUAY }}
          tags: |
              ${{ matrix.fedora_release }}
              ${{ matrix.fedora_release }}.${{ needs.generate-matrix.outputs.version }}

      - name: "Push Intel image to Container Registry (quay.io)"
        uses: redhat-actions/push-to-registry@v3
        id: push_quay_io_intel
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          username: ${{ secrets.BOT_USERNAME }}
          password: ${{ secrets.BOT_SECRET }}
          image: ${{ env.REPO_NAME }}/${{ matrix.variant }}-intel
          registry: ${{ env.REGISTRY_QUAY }}
          tags: |
              ${{ matrix.fedora_release }}
              ${{ matrix.fedora_release }}.${{ needs.generate-matrix.outputs.version }}

      - name: "Push AMD image to Container Registry (quay.io)"
        uses: redhat-actions/push-to-registry@v3
        id: push_quay_io_amd
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          username: ${{ secrets.BOT_USERNAME }}
          password: ${{ secrets.BOT_SECRET }}
          image: ${{ env.REPO_NAME }}/${{ matrix.variant }}-amd
          registry: ${{ env.REGISTRY_QUAY }}
          tags: |
              ${{ matrix.fedora_release }}
              ${{ matrix.fedora_release }}.${{ needs.generate-matrix.outputs.version }}

      - name: "Push NVIDIA image to Container Registry (quay.io)"
        uses: redhat-actions/push-to-registry@v3
        id: push_quay_io_nvidia
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          username: ${{ secrets.BOT_USERNAME }}
          password: ${{ secrets.BOT_SECRET }}
          image: ${{ env.REPO_NAME }}/${{ matrix.variant }}-nvidia
          registry: ${{ env.REGISTRY_QUAY }}
          tags: |
              ${{ matrix.fedora_release }}
              ${{ matrix.fedora_release }}.${{ needs.generate-matrix.outputs.version }}

      - name: "Sign generic container image (quay.io)"
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ env.REGISTRY_QUAY }}/${{ env.REPO_NAME }}/${{ matrix.variant }}@${{ steps.push_quay_io.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

      - name: "Sign Intel container image (quay.io)"
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ env.REGISTRY_QUAY }}/${{ env.REPO_NAME }}/${{ matrix.variant }}-intel@${{ steps.push_quay_io_intel.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

      - name: "Sign AMD container image (quay.io)"
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ env.REGISTRY_QUAY }}/${{ env.REPO_NAME }}/${{ matrix.variant }}-intel@${{ steps.push_quay_io_amd.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

      - name: "Sign NVIDIA container image (quay.io)"
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ env.REGISTRY_QUAY }}/${{ env.REPO_NAME }}/${{ matrix.variant }}-intel@${{ steps.push_quay_io_nvidia.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
