# SPDX-FileCopyrightText: Timothée Ravier <tim@siosm.fr>
# SPDX-License-Identifier: CC0-1.0

name: "Build Sealed Bootable Container images"

env:
  REGISTRY: "ghcr.io/${{ github.repository_owner }}"
  REPO_NAME: "${{ github.event.repository.name }}"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: '0 4 * * MON'
  workflow_dispatch:

# Allow:
# - Read access to the repo content
# - Write access to packages to allow access to GitHub container registry
permissions:
  contents: "read"
  packages: "write"

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentialy for the main branch. Also cancel in progress workflow runs for
# pull requests only.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-image:
    runs-on: "ubuntu-24.04"
    strategy:
      fail-fast: false
      matrix:
        variant: ['silverblue', 'kinoite']
        version: ['44']
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v6

      - name: "Runner setup"
        uses: travier/bootc-dev-actions/bootc-ubuntu-setup@main

      - name: "Login to Container Registry"
        uses: redhat-actions/podman-login@v1
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Generate version"
        id: version
        run: |
          set -euxo pipefail
          version="$(date '+%Y%m%d.0')"
          echo "Using version: ${version}"
          echo "version=${version}" >> "$GITHUB_OUTPUT"

      - name: "Get Secure Boot signing key"
        run: |
          mkdir -p /tmp/keys
          printenv SB_KEY > /tmp/keys/key
          printenv SB_CRT > /tmp/keys/crt
        env:
          SB_KEY: ${{ secrets.SB_KEY }}
          SB_CRT: ${{ secrets.SB_CRT }}

      - name: "Build container image"
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.REPO_NAME }}/${{ matrix.variant }}
          tags: ${{ matrix.version }}.${{ steps.version.outputs.version }} ${{ matrix.version }}
          containerfiles: Containerfile
          layers: false
          oci: true
          build-args: |
            BASE=quay.io/fedora-ostree-desktops/${{ matrix.variant }}:${{ matrix.version }}.${{ steps.version.outputs.version }}
            SYSTEMDBOOT=quay.io/fedora-atomic-desktops-sealed/systemd-boot:${{ matrix.version }}
            TOOLS=quay.io/fedora-atomic-desktops-sealed/tools:${{ matrix.version }}
          extra-args: |
            --skip-unused-stages=false
            --security-opt=label=disable
            --volume /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}:/run/src
            --secret=id=secureboot_key,src=key
            --secret=id=secureboot_crt,src=crt

      - name: "Cleanup Secure Boot signing key"
        if: always()
        run: rm -vrf /tmp/keys

      - name: "Setup cosign"
        uses: sigstore/cosign-installer@v3.10.0
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'

      - name: "Push to Container Registry"
        uses: redhat-actions/push-to-registry@v2
        id: push
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ env.REPO_NAME }}/${{ matrix.variant }}
          registry: ${{ env.REGISTRY }}
          tags: ${{ matrix.version }}.${{ steps.version.outputs.version }} ${{ matrix.version }}

      - name: "Sign container image"
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ env.REGISTRY }}/${{ env.REPO_NAME }}/${{ matrix.variant }}@${{ steps.push.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
