# SPDX-FileCopyrightText: Timothée Ravier <tim@siosm.fr>
# SPDX-License-Identifier: CC0-1.0

name: "Build QCOW2 images"

env:
  REGISTRY_GHCR: "ghcr.io/${{ github.repository_owner }}"
  REGISTRY_QUAY: "quay.io"
  REPO_NAME: "${{ github.event.repository.name }}"

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/disk-images.yml"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/disk-images.yml"
  schedule:
    - cron: '0 4 * * MON'
  workflow_dispatch:

# Allow:
# - Read access to the repo content
# - Write access to packages to allow access to GitHub container registry
permissions:
  contents: "read"
  packages: "write"

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentialy for the main branch. Also cancel in progress workflow runs for
# pull requests only.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-image:
    runs-on: "ubuntu-24.04"
    strategy:
      fail-fast: false
      matrix:
        variant: ['silverblue', 'kinoite']
        version: ['44']
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v6

      - name: "Runner setup"
        uses: travier/bootc-dev-actions/bootc-ubuntu-setup@main
        with:
          libvirt: true

      - name: "Login to Container Registry (ghcr.io)"
        uses: redhat-actions/podman-login@v1
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          registry: ${{ env.REGISTRY_GHCR }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # FIXME
      # version="$(\
      #   skopeo inspect --no-tags docker://${REGISTRY_GHCR}/${REPO_NAME}/${VARIANT}:${VERSION} \
      #   | jq -r '.Labels."org.opencontainers.image.version"'
      # )"
      - name: "Find version"
        id: version
        run: |
          set -euxo pipefail
          version="$(date '+%Y%m%d.0')"
          echo "Using version: ${version}"
          echo "version=${version}" >> "$GITHUB_OUTPUT"

      - name: "Build disk image"
        run: |
          set -euxo pipefail
          podman pull ${REGISTRY_QUAY}/${REPO_NAME}/${VARIANT}:${VERSION}
          bcvk to-disk \
            --filesystem=btrfs \
            --composefs-backend \
            --bootloader=systemd \
            --format qcow2 \
            --disk-size 20G \
            ${REGISTRY_QUAY}/${REPO_NAME}/${VARIANT}:${VERSION} \
            ${VARIANT}-${VERSION}.qcow2
        env:
          VARIANT: ${{ matrix.variant }}
          VERSION: ${{ matrix.version }}

      - name: "Install oras CLI"
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        uses: oras-project/setup-oras@v1

      - name: "Setup cosign"
        uses: sigstore/cosign-installer@v3.10.0
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'

      - name: "Login to Container Registry (quay.io)"
        uses: redhat-actions/podman-login@v1
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          registry: ${{ env.REGISTRY_QUAY }}
          username: ${{ secrets.BOT_USERNAME }}
          password: ${{ secrets.BOT_SECRET }}

      - name: "Upload disk image as OCI artifact with oras"
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        id: "push"
        shell: bash
        run: |
          output="$(
            oras push \
              --annotation "quay.expires-after=4w" \
              --format json \
              ${REGISTRY_QUAY}/${REPO_NAME}/${VARIANT}:${VERSION}.qcow2 \
              "${VARIANT}-${VERSION}.qcow2":application/vnd.qcow2.image
          )"
          echo "oras output: ${output}"
          digest="$(echo "${output}" | jq --raw-output '.digest')"
          echo "digest=${digest}" >> "$GITHUB_OUTPUT"
        env:
          VARIANT: ${{ matrix.variant }}
          VERSION: ${{ matrix.version }}

      - name: "Sign artifact (quay.io)"
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ env.REGISTRY_QUAY }}/${{ env.REPO_NAME }}/${{ matrix.variant }}@${{ steps.push.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
