# SPDX-FileCopyrightText: Timothée Ravier <tim@siosm.fr>
# SPDX-License-Identifier: CC0-1.0

name: "Build systemd-boot container image"

env:
  CONTAINERFILE: "Containerfile.systemd-boot"
  NAME: "${{ github.event.repository.name }}/systemd-boot"
  REGISTRY_GHCR: "ghcr.io/${{ github.repository_owner }}"
  REGISTRY_QUAY: "quay.io"

on:
  # Only build on demand as we don't want to resign systemd-boot if there are
  # no updates as it might change the PCR values (TBC).
  workflow_dispatch:

# Allow:
# - Read access to the repo content
# - Write access to packages to allow access to GitHub container registry
permissions:
  contents: "read"
  packages: "write"

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentialy for the main branch. Also cancel in progress workflow runs.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-x86_64:
    runs-on: "ubuntu-24.04"
    strategy:
      fail-fast: false
      matrix:
        release: ['44']
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v6

      - name: "Runner setup"
        uses: travier/bootc-dev-actions/bootc-ubuntu-setup@main
        with:
          freespace: false

      - name: "Get Secure Boot signing key"
        run: |
          mkdir -p /tmp/keys
          printenv SB_KEY > /tmp/keys/key
          printenv SB_CRT > /tmp/keys/crt
        env:
          SB_KEY: ${{ secrets.SB_KEY }}
          SB_CRT: ${{ secrets.SB_CRT }}

      - name: "Build container image"
        uses: redhat-actions/buildah-build@v2
        with:
          context: ".github"
          image: ${{ env.NAME }}
          tags: ${{ matrix.release }}-x86_64
          containerfiles: ${{ env.CONTAINERFILE }}
          oci: true
          build-args: |
            RELEASE=${{ matrix.release }}
          extra-args: |
            --secret=id=secureboot_key,src=/tmp/keys/key
            --secret=id=secureboot_crt,src=/tmp/keys/crt

      - name: "Cleanup Secure Boot signing key"
        if: always()
        run: rm -vrf /tmp/keys

      - name: "Push to Container Registry (ghcr.io)"
        uses: redhat-actions/push-to-registry@v2
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          registry: ${{ env.REGISTRY_GHCR }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ env.NAME }}
          tags: ${{ matrix.release }}-x86_64

      - name: "Push to Container Registry (quay.io)"
        uses: redhat-actions/push-to-registry@v2
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          registry: ${{ env.REGISTRY_QUAY }}
          username: ${{ secrets.BOT_USERNAME }}
          password: ${{ secrets.BOT_SECRET }}
          image: ${{ env.NAME }}
          tags: ${{ matrix.release }}-x86_64

  # build-aarch64:
  #   runs-on: "ubuntu-24.04-arm"
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       release: ['44']
  #   steps:
  #     - name: "Checkout repo"
  #       uses: actions/checkout@v5

  #     - name: "Build container image"
  #       uses: redhat-actions/buildah-build@v2
  #       with:
  #         context: ".github"
  #         image: ${{ env.NAME }}
  #         tags: ${{ matrix.release }}-aarch64
  #         containerfiles: ${{ env.CONTAINERFILE }}
  #         oci: true
  #         build-args: |
  #           RELEASE=${{ matrix.release }}

  #     - name: "Push to Container Registry"
  #       uses: redhat-actions/push-to-registry@v2
  #       id: "push"
  #       if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
  #       with:
  #         registry: ${{ env.REGISTRY }}
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #         image: ${{ env.NAME }}
  #         tags: ${{ matrix.release }}-aarch64

  merge:
    runs-on: "ubuntu-24.04"
    needs:
      - "build-x86_64"
      # - "build-aarch64"
    strategy:
      fail-fast: false
      matrix:
        release: ['44']
    steps:
      - name: "Login to Container Registry (ghcr.io)"
        uses: redhat-actions/podman-login@v1
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          registry: ${{ env.REGISTRY_GHCR }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Create multi-arch manifest"
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        shell: bash
        run: |
          set -euxo pipefail
          #   "${REGISTRY_GHCR}/${NAME}:${RELEASE}-aarch64"
          buildah manifest create "${REGISTRY_GHCR}/${NAME}:${RELEASE}" \
            "${REGISTRY_GHCR}/${NAME}:${RELEASE}-x86_64"
        env:
          RELEASE: ${{ matrix.release }}

      - name: "Push to Container Registry (ghcr.io)"
        uses: redhat-actions/push-to-registry@v2
        id: "push"
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          registry: ${{ env.REGISTRY_GHCR }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ env.NAME }}
          tags: ${{ matrix.release }}

      - name: "Setup cosign"
        uses: sigstore/cosign-installer@v4.1.1
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'

      - name: "Sign container image (ghcr.io)"
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ env.REGISTRY_GHCR }}/${{ env.NAME }}@${{ steps.push.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

      - name: "Login to Container Registry (quay.io)"
        uses: redhat-actions/podman-login@v1
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          registry: ${{ env.REGISTRY_QUAY }}
          username: ${{ secrets.BOT_USERNAME }}
          password: ${{ secrets.BOT_SECRET }}

      - name: "Create multi-arch manifest"
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        shell: bash
        run: |
          set -euxo pipefail
          #   "${REGISTRY_QUAY}/${NAME}:${RELEASE}-aarch64"
          buildah manifest create "${REGISTRY_QUAY}/${NAME}:${RELEASE}" \
            "${REGISTRY_QUAY}/${NAME}:${RELEASE}-x86_64"
        env:
          RELEASE: ${{ matrix.release }}

      - name: "Push to Container Registry (quay.io)"
        uses: redhat-actions/push-to-registry@v2
        id: push_quay_io
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          username: ${{ secrets.BOT_USERNAME }}
          password: ${{ secrets.BOT_SECRET }}
          image: ${{ env.NAME }}
          registry: ${{ env.REGISTRY_QUAY }}
          tags: ${{ matrix.release }}

      - name: "Sign container image (quay.io)"
        if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ env.REGISTRY_QUAY }}/${{ env.NAME }}@${{ steps.push_quay_io.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
